Lerbaek.NetDaemon.Apps.Integrations.Nordlux.Configuration.NordluxConfig:
  AppCode: nordlux
  AppVersion: 2.4.0
  BuildVersion: 120
  MobileSystemType: android
  ApiVersions:
    ReportBulbRequest: 1.2.0
    GetDeviceStatus: 2.0.0
    ControllerBle: 2.0.0